### ISSUE TITLE
com.civisanalytics.gephi.GephiForceDiagramException: Could not access column centrality in graph

### ISSUE THREAD

**Issue by tiramisutes** [civisanalytics/GephiForceDiagramTool#5]
Dear,
I clone the GephiForceDiagramTool from Github and successful run `./gradlew build`.
But there is stderr when running `./gradlew runClimateTest` as follows show:
```
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:runClimateTest
Aug 11, 2018 2:25:23 PM org.netbeans.modules.masterfs.watcher.Watcher getNotifierForPlatform
INFO: Native file watcher is disabled
Aug 11, 2018 2:25:23 PM org.gephi.io.processor.plugin.DefaultProcessor process
INFO: # Nodes loaded: 0
Aug 11, 2018 2:25:23 PM org.gephi.io.processor.plugin.DefaultProcessor process
INFO: # Edges loaded: 0
com.civisanalytics.gephi.GephiForceDiagramException: Could not access column centrality in graph
        at com.civisanalytics.gephi.GephiUtils.validateColumn(GephiUtils.java:162)
        at com.civisanalytics.gephi.GephiForceDiagram.validateColumns(GephiForceDiagram.java:565)
        at com.civisanalytics.gephi.GephiForceDiagram.run(GephiForceDiagram.java:281)
        at com.civisanalytics.gephi.CreateGephiForceDiagram.main(CreateGephiForceDiagram.java:230)
:runClimateTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClimateTest'.
> Process 'command '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-3.b17.el7.x86_64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.229 secs
```

Any help is much appreciated.
Thanks.

**Comment by DerrickHiggins** [comment]
Hmm.  Looks like it is not successfully loading the test file `data/climatechange.gml` (0 nodes/edges loaded).  Can you verify that the file exists and is not corrupted?

What's your platform & Java version?

**Comment by tiramisutes** [comment]
Sorry. I have a mistake. I just see the climatechange.gml file in the data directory, but it's incomplete.
By the way, I have another question. I just want to do the force_atlas2 calculate in GephiForceDiagramTool and then further adjust the visualization results using Gephi at Windows. But GephiForceDiagramTool only outputs a png figure.

**Comment by DerrickHiggins** [comment]
Right; there is currently no support for saving the final state of the Gephi object into a format that can be further edited using the GUI application.  You may be able to use [WorkspacePersistenceProvider](https://gephi.org/docs/api/org/gephi/project/spi/WorkspacePersistenceProvider.html) to implement this functionality; I'm happy to look at a pull request.  Or create an issue -- although I probably won't get around to adding that any time soon.

**Comment by tiramisutes** [comment]
Ok, Thanks for the reply. I will try.
